#+OPTIONS: ':nil *:nil -:t ::t <:t H:3 \n:nil ^:{} arch:headline author:t broken-links:mark
#+OPTIONS: c:nil creator:t d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:2
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t title:t toc:2
#+OPTIONS: todo:t |:t
#+TITLE: Director Configs for Macathon Nov. 2018
#+DATE: [2018-11-13 Tue]
#+AUTHOR: Gregory Grubbs
#+EMAIL: gregoryg@cloudera.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.1 (Org mode 9.0.1)
#+SETUPFILE: https://raw.githubusercontent.com/fniessen/org-html-themes/master/setup/theme-readtheorg.setup

* macathon-director

Configs for using Cloudera Altus Director

The emphasis on this training is:
   + Install third party and beta products using Director
   + Choose modular methods for HA and components
   + Resuse bootstrap scripts for different environments
   + Automatically bring up CDSW with wildcard DNS


* Pre-work - set up prior to Cloud Training on [2018-11-19 Mon]

Prior to coming to the Cloud hands on lab, please assure you have access and some
familiarity with the cloud console of your choice: AWS, GCP or Azure. 


** Clone the Macathon repository to your workstation
#+BEGIN_SRC sh
  git clone git@github.com:gregoryg/macathon-director.git
#+END_SRC

The examples below assume you will be using the SA or SE Azure subscription.

If you are familiar with cloud platforms, please consider using either GCP or AWS instead,
as we are very likely to run out of Azure resources during the hands on lab.  You can
modify the config files in the =macathon-director= repo - pull requests are very welcome!

** Install Azure command line client

 Documentation: [[https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest][Install the Azure CLI]]

 #+BEGIN_SRC sh
   brew update && brew install azure-cli
 #+END_SRC

** Configure Azure CLI
 #+BEGIN_SRC sh
   az login
 #+END_SRC


* Work to be done during Macathon training on [2018-11-19 Mon]
** Set up an instance for Cloudera Altus Director

 Script to use to provision and configure a Director instance: [[file:bin/provision-azure.sh][provision-azure.sh]]

 We'll be using Director 6.0, which is capable of bringing up CDH 6 and 5x clusters.

 The instance will include MariaDB on Centos 7, which will be used for the Director
 database.  This same instance may be used for the metadata database used by your
 Director-instantiated clusters.

 This instance will also run the =bind= DNS server, which on Azure is a necessity.  Our
 setup scrpit will add a rule to serve wildcard DNS for use by Cloudera Data Science
 Workbench.

*** Provision, install and configure your Altus Director instance
Use the script provided in the =macathon-director= repository you downloaded.

An example of usage of the provisioning script is shown below.

#+BEGIN_SRC sh
  OWNER_TAG=jsmith SSH_USERNAME=jsmith AZ_RESOURCE_GROUP=jsmith-rg SSH_KEYNAME=jsmith-azure.pub AZ_INSTANCE_NAME=js-director time ./provision-azure.sh 
#+END_SRC

** Bring up a cluster using your Altus Director instance

 The config file and supporting scripts are found in your home directory under =macathon-director=

 Config being used for this workshop is in =configs/cdh5-cdsw1-director2.conf=

 Edit =providers/azure-provider.conf= with your Azure credentials

 Edit =azure-instance-defaults.conf= with your resource names: resource group(s), Vnet, network security group, subnet

 Edit =cdh5-cdsw1-director2.conf= and add your private SSH key (you will need to copy that key to the instance)

 Review the environment variables in the first few lines of the config, and set them to your preference.  

 Launch the CLI to create the cluster.  An example of the command line:
 #+BEGIN_SRC sh
   OWNER_TAG=jsmith INSTANCE_PREFIX=js cloudera-director bootstrap-remote cdh5-cdsw1-director2.conf
 #+END_SRC

** Ingest data and test Hue/Hive/Impala/CDSW et al
    Some public data source ingest scripts may be found [[https://github.com/gregoryg/cdh-projects/tree/master/ingest][here]]
** Additional Resources for Altus Director configurations

 [[https://github.com/cloudera/director-scripts]] - look in =configs= directory

 [[https://github.com/gregoryg/cdh-projects]]


